# Generated by Django 4.1.7 on 2023-03-01 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grades", "0003_alter_grade_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="note",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
