# Generated by Django 4.1.7 on 2023-03-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subjects", "0004_rename_user_subject_teacher"),
        ("grades", "0004_alter_grade_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="subjects.subject"
            ),
        ),
    ]
