# Generated by Django 4.1.7 on 2023-02-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="subjects",
            field=models.ManyToManyField(
                related_name="subjects", to="subjects.subject"
            ),
        ),
    ]
