# Generated by Django 4.1.7 on 2023-02-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="year",
            field=models.CharField(max_length=50),
        ),
    ]
