# Generated by Django 4.1.7 on 2023-02-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subject",
            old_name="name_subject",
            new_name="name",
        ),
    ]
