# Generated by Django 4.1.7 on 2023-02-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0003_rename_name_subject_subject_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subject",
            old_name="user",
            new_name="teacher",
        ),
    ]
